#!/bin/bash

make
./prkt
read -p "Hit ENTER to continue"
octave plotQ.m &>/dev/null
xdg-open 'Q.png' &
read -p "Hit ENTER to continue"
octave plotL.m &>/dev/null
xdg-open 'L.png' &
read -p "Hit ENTER to end"